// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type BpfDnsDataT struct {
	_         structs.HostLayout
	Timestamp uint64
	Pid       uint32
	Tid       uint32
	Uid       uint32
	Daddr     uint32
	Dport     uint16
	Comm      [16]int8
	Query     [128]int8
}

type BpfFsDataT struct {
	_         structs.HostLayout
	Timestamp uint64
	Pid       uint32
	Tid       uint32
	Uid       uint32
	Flags     int32
	Comm      [16]int8
	Filename  [256]int8
}

type BpfMemDataT struct {
	_         structs.HostLayout
	Timestamp uint64
	Pid       uint32
	Tid       uint32
	Uid       uint32
	_         [4]byte
	Addr      uint64
	Len       uint64
	Prot      int32
	Flags     int32
	Comm      [16]int8
}

type BpfModDataT struct {
	_         structs.HostLayout
	Timestamp uint64
	Pid       uint32
	Tid       uint32
	Uid       uint32
	Comm      [16]int8
	ModName   [64]int8
}

type BpfNetDataT struct {
	_         structs.HostLayout
	Timestamp uint64
	Pid       uint32
	Tid       uint32
	Uid       uint32
	Saddr     uint32
	Daddr     uint32
	Sport     uint16
	Dport     uint16
	Action    int32
	Comm      [16]int8
}

type BpfProcDataT struct {
	_         structs.HostLayout
	Timestamp uint64
	Pid       uint32
	Tid       uint32
	Uid       uint32
	Ppid      uint32
	Action    int32
	ExitCode  int32
	Comm      [16]int8
	Filename  [256]int8
}

type BpfSyscallDataT struct {
	_         structs.HostLayout
	Timestamp uint64
	Pid       uint32
	Tid       uint32
	Uid       uint32
	_         [4]byte
	Nr        int64
	Args      [3]uint64
	Comm      [16]int8
}

// LoadBpf returns the embedded CollectionSpec for Bpf.
func LoadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Bpf: %w", err)
	}

	return spec, err
}

// LoadBpfObjects loads Bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*BpfObjects
//	*BpfPrograms
//	*BpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// BpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfSpecs struct {
	BpfProgramSpecs
	BpfMapSpecs
	BpfVariableSpecs
}

// BpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfProgramSpecs struct {
	TraceDnssendto      *ebpf.ProgramSpec `ebpf:"trace_dns_sendto"`
	TraceDoInitModule   *ebpf.ProgramSpec `ebpf:"trace_do_init_module"`
	TraceFsOpenat       *ebpf.ProgramSpec `ebpf:"trace_fs_openat"`
	TraceMemMmap        *ebpf.ProgramSpec `ebpf:"trace_mem_mmap"`
	TraceProcessExec    *ebpf.ProgramSpec `ebpf:"trace_process_exec"`
	TraceProcessExit    *ebpf.ProgramSpec `ebpf:"trace_process_exit"`
	TraceSysEnter       *ebpf.ProgramSpec `ebpf:"trace_sys_enter"`
	TraceTcpV4Connect   *ebpf.ProgramSpec `ebpf:"trace_tcp_v4_connect"`
	TraceTcpV6Connect   *ebpf.ProgramSpec `ebpf:"trace_tcp_v6_connect"`
}

// BpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfMapSpecs struct {
	DnsEvents     *ebpf.MapSpec `ebpf:"dns_events"`
	FsEvents      *ebpf.MapSpec `ebpf:"fs_events"`
	MemEvents     *ebpf.MapSpec `ebpf:"mem_events"`
	ModEvents     *ebpf.MapSpec `ebpf:"mod_events"`
	NetEvents     *ebpf.MapSpec `ebpf:"net_events"`
	ProcEvents    *ebpf.MapSpec `ebpf:"proc_events"`
	SyscallEvents *ebpf.MapSpec `ebpf:"syscall_events"`
}

// BpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfVariableSpecs struct {
	UnusedDns     *ebpf.VariableSpec `ebpf:"unused_dns"`
	UnusedFs      *ebpf.VariableSpec `ebpf:"unused_fs"`
	UnusedMem     *ebpf.VariableSpec `ebpf:"unused_mem"`
	UnusedMod     *ebpf.VariableSpec `ebpf:"unused_mod"`
	UnusedNet     *ebpf.VariableSpec `ebpf:"unused_net"`
	UnusedProc    *ebpf.VariableSpec `ebpf:"unused_proc"`
	UnusedSyscall *ebpf.VariableSpec `ebpf:"unused_syscall"`
}

// BpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfObjects struct {
	BpfPrograms
	BpfMaps
	BpfVariables
}

func (o *BpfObjects) Close() error {
	return _BpfClose(
		&o.BpfPrograms,
		&o.BpfMaps,
	)
}

// BpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfMaps struct {
	DnsEvents     *ebpf.Map `ebpf:"dns_events"`
	FsEvents      *ebpf.Map `ebpf:"fs_events"`
	MemEvents     *ebpf.Map `ebpf:"mem_events"`
	ModEvents     *ebpf.Map `ebpf:"mod_events"`
	NetEvents     *ebpf.Map `ebpf:"net_events"`
	ProcEvents    *ebpf.Map `ebpf:"proc_events"`
	SyscallEvents *ebpf.Map `ebpf:"syscall_events"`
}

func (m *BpfMaps) Close() error {
	return _BpfClose(
		m.DnsEvents,
		m.FsEvents,
		m.MemEvents,
		m.ModEvents,
		m.NetEvents,
		m.ProcEvents,
		m.SyscallEvents,
	)
}

// BpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfVariables struct {
	UnusedDns     *ebpf.Variable `ebpf:"unused_dns"`
	UnusedFs      *ebpf.Variable `ebpf:"unused_fs"`
	UnusedMem     *ebpf.Variable `ebpf:"unused_mem"`
	UnusedMod     *ebpf.Variable `ebpf:"unused_mod"`
	UnusedNet     *ebpf.Variable `ebpf:"unused_net"`
	UnusedProc    *ebpf.Variable `ebpf:"unused_proc"`
	UnusedSyscall *ebpf.Variable `ebpf:"unused_syscall"`
}

// BpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfPrograms struct {
	TraceDnsendto    *ebpf.Program `ebpf:"trace_dns_sendto"`
	TraceDoInitModule *ebpf.Program `ebpf:"trace_do_init_module"`
	TraceFsOpenat    *ebpf.Program `ebpf:"trace_fs_openat"`
	TraceMemMmap     *ebpf.Program `ebpf:"trace_mem_mmap"`
	TraceProcessExec *ebpf.Program `ebpf:"trace_process_exec"`
	TraceProcessExit *ebpf.Program `ebpf:"trace_process_exit"`
	TraceSysEnter    *ebpf.Program `ebpf:"trace_sys_enter"`
	TraceTcpV4Connect *ebpf.Program `ebpf:"trace_tcp_v4_connect"`
	TraceTcpV6Connect *ebpf.Program `ebpf:"trace_tcp_v6_connect"`
}

func (p *BpfPrograms) Close() error {
	return _BpfClose(
		p.TraceDnsendto,
		p.TraceDoInitModule,
		p.TraceFsOpenat,
		p.TraceMemMmap,
		p.TraceProcessExec,
		p.TraceProcessExit,
		p.TraceSysEnter,
		p.TraceTcpV4Connect,
		p.TraceTcpV6Connect,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfel.o
var _BpfBytes []byte
